// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZ_AEzYW9pgJi6pOVKmQxLMkU0DMaKhQ',
    appId: '1:254977956580:web:a2ed8b2e357536e05f2af1',
    messagingSenderId: '254977956580',
    projectId: 'planitagenda',
    authDomain: 'planitagenda.firebaseapp.com',
    storageBucket: 'planitagenda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCIWHfpTFUO-XDTC-3zlhSnXR2_W-hW3o',
    appId: '1:254977956580:android:07c5542b246d40185f2af1',
    messagingSenderId: '254977956580',
    projectId: 'planitagenda',
    storageBucket: 'planitagenda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgwJReM259dn4TySSKAmHAZWRuWIkNdI',
    appId: '1:254977956580:ios:3e58f5fff8fb931a5f2af1',
    messagingSenderId: '254977956580',
    projectId: 'planitagenda',
    storageBucket: 'planitagenda.appspot.com',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtgwJReM259dn4TySSKAmHAZWRuWIkNdI',
    appId: '1:254977956580:ios:3e58f5fff8fb931a5f2af1',
    messagingSenderId: '254977956580',
    projectId: 'planitagenda',
    storageBucket: 'planitagenda.appspot.com',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHZ_AEzYW9pgJi6pOVKmQxLMkU0DMaKhQ',
    appId: '1:254977956580:web:81c6c0f73903a0b95f2af1',
    messagingSenderId: '254977956580',
    projectId: 'planitagenda',
    authDomain: 'planitagenda.firebaseapp.com',
    storageBucket: 'planitagenda.appspot.com',
  );

}