// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCYImeh9hpYWbLhPxXOgv6qHTKXW0t9SA',
    appId: '1:302461195077:web:edc74f85df19bf4ffde42c',
    messagingSenderId: '302461195077',
    projectId: 'planit-b08e2',
    authDomain: 'planit-b08e2.firebaseapp.com',
    storageBucket: 'planit-b08e2.appspot.com',
    measurementId: 'G-LB7FMSMV7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GTYIqjdlMTo3W1HExKIQE2m5hrFqCbE',
    appId: '1:302461195077:android:099b1c0f5df57d21fde42c',
    messagingSenderId: '302461195077',
    projectId: 'planit-b08e2',
    storageBucket: 'planit-b08e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNrRWMTr99j60CeNssQwYRwlUU8-gv0M',
    appId: '1:302461195077:ios:5d7dd1d79e4809fcfde42c',
    messagingSenderId: '302461195077',
    projectId: 'planit-b08e2',
    storageBucket: 'planit-b08e2.appspot.com',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNrRWMTr99j60CeNssQwYRwlUU8-gv0M',
    appId: '1:302461195077:ios:5d7dd1d79e4809fcfde42c',
    messagingSenderId: '302461195077',
    projectId: 'planit-b08e2',
    storageBucket: 'planit-b08e2.appspot.com',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCYImeh9hpYWbLhPxXOgv6qHTKXW0t9SA',
    appId: '1:302461195077:web:51fff2853d447d6cfde42c',
    messagingSenderId: '302461195077',
    projectId: 'planit-b08e2',
    authDomain: 'planit-b08e2.firebaseapp.com',
    storageBucket: 'planit-b08e2.appspot.com',
    measurementId: 'G-PB2FR9XHFE',
  );

}